# Generated by Django 3.1.7 on 2023-04-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230411_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hastags',
            new_name='hashtags',
        ),
    ]
